#!/usr/bin/env python
# -*- coding: utf-8 -*-

set $mod Mod4
set $term rxvt-unicode

set $black       #282828
set $darkblack   #1d2021
set $transparent #34444444
set_from_resource $fg i3wm.color7 #f0f0f0
set_from_resource $bg i3wm.color2 #f0f0f0

# class                 border  backgr. text indicator child_border
client.focused          $bg     $bg     $fg  $bg       $bg
client.focused_inactive $bg     $bg     $fg  $bg       $bg
client.unfocused        $bg     $bg     $fg  $bg       $bg
client.urgent           $bg     $bg     $fg  $bg       $bg
client.placeholder      $bg     $bg     $fg  $bg       $bg

client.background       $bg
font pango:'Inconsolata for Powerline' 10
for_window [class="^.*"] border pixel 1
new_window 1pixel

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec $term 

# kill focused window
bindsym $mod+q kill

bindsym $mod+d exec rofi -show run
# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# Custom Launchers k2
bindsym $mod+Shift+f exec google-chrome
bindsym $mod+Shift+p exec pgadmin3
bindsym $mod+Shift+t exec qbittorrent

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+g split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+Shift+w layout stacked
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
bindsym $mod+Shift+a focus child

set $ws1  " "
set $ws2  " "
set $ws3  " "
set $ws4  " "
set $ws5  ""
set $ws6  " "
set $ws7  " "
set $ws8  ""
set $ws9  " "
set $ws10  " "

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

assign [class="(?i)google-chrome"]        $ws1
assign [title="(?i)rxvt-unicode"]         $ws2
assign [class="(?i)torrent"]              $ws3
assign [title="(?i)steam"]                $ws4
assign [title="(?i)ranger"]               $ws5
assign [class="(?i)pgadmin"]              $ws6
assign [title="(?i)ncmpcpp"]              $ws7
assign [class="(?i)mpv"]                  $ws8
assign [title="(?i)mutt"]                 $ws9
assign [class="(?i)gnome-system-monitor"] $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i4 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
bindsym $mod+Shift+backspace reboot
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+o exit
bindsym $mod+z mode "resize"
bindsym $mod+s mode "system"
bindsym $mod+w mode "wallpapers"
bindsym $mod+m mode "mail"
bindsym $mod+p mode "programs"
bindsym $mod+Shift+d mode "distraction_free"
bindsym $mod+Shift+m mode "music"
bindsym $mod+Shift+b mode "brightness"
bindsym $mod+Shift+g mode "$mode_gaps"

set $mode_gaps Gaps: (o) outer, (i) inner
set $mode_gaps_outer Outer Gaps: +|-|0 (local), Shift + +|-|0 (global)
set $mode_gaps_inner Inner Gaps: +|-|0 (local), Shift + +|-|0 (global)

mode "wallpapers" {
        bindsym z exec "wal -i $HOME/HD/Pictures/Wallpapers/Retrowave -o $HOME/HD/Pictures/Wallpapers/restart.sh"
        bindsym x exec "wal -i $HOME/HD/Pictures/Wallpapers/Vibrant -o $HOME/HD/Pictures/Wallpapers/restart.sh"
        bindsym c exec "wal -i $HOME/HD/Pictures/Wallpapers/Future -o $HOME/HD/Pictures/Wallpapers/restart.sh"
        bindsym v exec "wal -i $HOME/HD/Pictures/Wallpapers/Landscapes -o $HOME/HD/Pictures/Wallpapers/restart.sh"
        bindsym b exec "wal -i $HOME/HD/Pictures/Wallpapers/Cityscapes -o $HOME/HD/Pictures/Wallpapers/restart.sh"
        bindsym a exec "wal -i $(find $HOME/HD/Pictures/Wallpapers/** -name '*.**g' | shuf -n 1) -o $HOME/HD/Pictures/Wallpapers/restart.sh"
        bindsym Return mode "default"
}

mode "distraction_free" {
    bindsym d exec "~/dist_free_disable.sh"
    bindsym e exec  "~/dist_free_enable.sh"
    bindsym Return mode "default"
}

mode "programs" {
        bindsym f exec firefox
        bindsym c exec google-chrome
        bindsym p exec pgadmin3
        bindsym s exec steam
        bindsym v exec $term -e vim
        bindsym m exec spotify
        bindsym q exec qbittorrent
        bindsym w exec playonlinux
        bindsym Shift+p exec postman
        bindsym Return mode "default"
}

mode "$mode_gaps" {
        bindsym o      mode "$mode_gaps_outer"
        bindsym i      mode "$mode_gaps_inner"
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

mode "$mode_gaps_inner" {
        bindsym plus  gaps inner current plus 5
        bindsym minus gaps inner current minus 5
        bindsym 0     gaps inner current set 0

        bindsym Shift+plus  gaps inner all plus 5
        bindsym Shift+minus gaps inner all minus 5
        bindsym Shift+0     gaps inner all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym Tab mode "$mode_gaps_outer"
}

mode "$mode_gaps_outer" {
        bindsym plus  gaps outer current plus 5
        bindsym minus gaps outer current minus 5
        bindsym 0     gaps outer current set 0

        bindsym Shift+plus  gaps outer all plus 5
        bindsym Shift+minus gaps outer all minus 5
        bindsym Shift+0     gaps outer all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym Tab mode "$mode_gaps_inner"
}

mode "mail" {
        bindsym s exec $term -hold -e mutt -F ~/.muttrc_lucas.fim
        bindsym p exec $term -hold -e mutt -F ~/.muttrc_lucas.thiago
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

mode "system" {
        bindsym s exec systemctl poweroff
        bindsym r exec systemctl reboot

        bindsym Return mode "default"
        bindsym Space  mode "default"
        bindsym Escape mode "default"
}

mode "music" {
        # todo: bind media keys
        bindsym k exec amixer -D pulse sset Master 5%+
        bindsym Shift+k exec amixer -D pulse sset Master 15%+
        bindsym Shift+j exec amixer -D pulse sset Master 15%-
        bindsym j exec amixer -D pulse sset Master 5%-
        
        bindsym l exec mpc next
        bindsym h exec mpc prev
        bindsym x exec mpc toggle
        bindsym p exec mpc toggle
        bindsym c exec mpc stop
        bindsym z exec mpc random

        bindsym Return mode "default"
        bindsym Space  mode "default"
        bindsym Escape mode "default"
}

mode "brightness" {
        bindsym k exec light -A 5
        bindsym j exec light -U 5
        bindsym Return mode "default"
        bindsym Space  mode "default"
        bindsym Escape mode "default"
}

mode "resize" {
        bindsym h resize shrink width 10 px or 10 ppt
        bindsym j resize grow height 10 px or 10 ppt
        bindsym k resize shrink height 10 px or 10 ppt
        bindsym l resize grow width 10 px or 10 ppt

        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        bindsym Return mode "default"
        bindsym Space  mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+Ctrl+Right resize shrink width  10px or  10ppt
bindsym $mod+Ctrl+Up resize grow height  10px or  10ppt
bindsym $mod+Ctrl+Down resize shrink height  10px or  10ppt
bindsym $mod+Ctrl+Left resize grow width  10px or  10ppt
bindsym $mod+r exec $term -e ranger
bindsym $mod+n exec $term -e ncmpcpp
bindsym $mod+Shift+Return exec $term -e tmux
bindsym $mod+Tab workspace next
bindsym $mod+Shift+Tab workspace prev
bindsym --release Print exec scrot -s ~/prints/print_%d_%m_%Y_%T.png
bindsym --release Shift+Print exec scrot ~/prints/print_%d_%m_%Y_%T.png
gaps inner 10
gaps outer 10

bar {
        font pango:Source Code Pro for Powerline, FontAwesome 11
        i3bar_command i3bar -t
        tray_output none
        status_command ~/bumblebee-status/bumblebee-status -m xrandr caffeine cpu sensors memory battery brightness pasink datetime -p brightness.wheel-up='light -A 5' brightness.wheel-down='light -U 5' datetime.format='%d/%m | %H:%M' memory.format='{used}' -t wal-powerline

        colors {
            statusline         $white
            background         $transparent
            separator          $transparent

            #                  BORDER       BACKGROUND   TEXT
            focused_workspace  $transparent $transparent $bg
            inactive_workspace $transparent $transparent $fg
            active_workspace   $transparent $transparent #39FF14
            urgent_workspace   $darkred     $darkred     $transparent
            binding_mode       $darkred     $darkred     $transparent
            }
        }

# exec --no-startup-id compton -b
exec --no-startup-id nm-applet

