#!/bin/bash

if [[ ! $DIST_FREE_FLAG ]]; then
	sudo sed -i '/facebook/d;/twitter/d;/reddit/d;/whatsapp/d' /etc/hosts
	DIST_FREE_FLAG=false
	#statements
fi
DIST_FREE_FLAG='false'
dist_free_disable() {
	sudo sed -i '/facebook/d;/twitter/d;/reddit/d;/whatsapp/d' /etc/hosts
	DIST_FREE_FLAG=false
}

dist_free_enable() {
	sudo sed -i '/facebook/d;/twitter/d;/reddit/d;/whatsapp/d' /etc/hosts
	sudo sed -i '$a\
0.0.0.0 www.facebook.com\
0.0.0.0 facebook.com\
0.0.0.0 www.twitter.com\
0.0.0.0 twitter.com\
0.0.0.0 www.reddit.com\
0.0.0.0 reddit.com\
0.0.0.0 www.web.whatsapp.com\
0.0.0.0 web.whatsapp.com\
	' /etc/hosts
	DIST_FREE_FLAG=true
}

dist_free_toggle() {
	if [ "$DIST_FREE_FLAG" = "true" ]; then
		dist_free_disable

	elif [ "$DIST_FREE_FLAG" = "false" ]; then
		dist_free_enable
	fi
}


