#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal
 # Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

 reload_dunst() {
    pkill dunst
    dunst \
        -lb "${color1}" \
        -nb "${color1}" \
        -cb "${color1}" \
        -lf "${color4}" \
        -bf "${color4}" \
        -cf "${color4}" \
        -nf "${color4}" &
}

reload_dunst
