#!/bin/bash

cd ~/_git/neofetch_git/
pwd
echo
git fetch --all
git pull
sudo make install
echo


cd ~/_git/ranger_git/
pwd
echo
git fetch --all
git pull
sudo python3 setup.py install
echo

cd ~/_git/pywal_git/
pwd
echo
git fetch --all
git pull
sudo python3 setup.py install
sudo pip3 install pywal --upgrade
echo

cd ~/i3-gaps/
git fetch --all
git pull
cd build
../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers	
sudo make install
echo

