#!/bin/bash
dotfiles_push() {
	cd ~/dotfiles
	sudo rm ./.vimrc
	sudo rm ./.Xdefaults
	sudo rm ./K2.fish
	sudo rm ./Xsession
	sudo rm -rf ./i3
	sudo rm -rf ./i3blocks
	sudo rm -rf ./ranger
	sudo rm -rf ./termite
	sudo rm -rf ./scripts

	mkdir scripts
	sudo cp ~/scripts/dist_free_toggle.sh ./scripts
	sudo cp ~/scripts/update_gits ./scripts
	sudo cp ~/scripts/update_dotfiles ./scripts
	sudo cp ~/.vimrc .
	sudo cp ~/.Xdefaults .
	sudo cp ~/scripts/K2.fish .
	sudo cp /etc/X11/Xsession ./Xsession
	sudo cp -r ~/.config/i3 ./i3
	sudo cp -r ~/.config/i3blocks/ .
	sudo cp -r ~/.config/ranger/ ./ranger
	cd ~
}

dotfiles_pull() {
	ls
	# TODO
}

dotfiles_push
