#!/bin/bash

. "/home/k2/.cache/wal/colors.sh"

print_light() {
  light | sed 's/\..*$/%/'
}


case $BLOCK_BUTTON in
  4) light -A 5 ;; # scroll up, increase
  5) light -U 5 ;; # scroll down, decrease
esac

echo "<span foreground=\"$color9\"> $(print_light)</span>"



