#!/bin/bash

. "/home/k2/.cache/wal/colors.sh"

OUTPUT=$(date '+%d/%m/%Y %H:%M')

case $BLOCK_BUTTON in
  1) gsimplecal
esac

echo "<span foreground=\"${color2}90\"></span><span background=\"${color2}90\" foreground=\"$background\">  $OUTPUT </span>"
