#!/bin/bash

. "/home/k2/.cache/wal/colors.sh"

print_todos() {
  wc -l ~/.todolist | sed 's/ .*$//'
}


case $BLOCK_BUTTON in
  1) rxvt-unicode -e vim ~/.todolist
esac

echo "<span foreground=\"$color7\"> $(print_todos)</span>"



